### ISSUE TITLE
Naming: Use capital letters for names of types

### ISSUE THREAD

**Issue by martinjonsson01** [adiwir/TDA553-lab1#12] opened 2022-12-06 08:45 UTC
In Java, all types (e.g. interfaces, classes, enums) should be capitalized. 

https://github.com/adiwir/TDA553-lab2/blob/7f26da90d6cb1168d4196ff6f273ef66f8bf6abc/src/labb/Car.java#L15

**Comment by JacobAndersso** [comment] 2022-12-06 11:06
Duplicate of #11

**Closed as completed** 2022-12-08 08:54 UTC
